version: '3.8'
services:
  chatbot-rag:
    build: ./chatbot-rag
    ports:
      - "7860:7860"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge