version: '3.8'
services:
  chatbot-rag:
    build: ./chatbot-rag
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - app-network
  gradio-ui:
    build: ./gradio-ui
    ports:
      - "7860:7860"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge